# Generated by Django 5.0 on 2024-01-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cumparat',
            new_name='achizitionat',
        ),
    ]
