# Generated by Django 5.0 on 2024-01-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShopping', '0003_item_greutate_item_pret_item_pret_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='achizitionat',
            new_name='cumparat',
        ),
        migrations.AlterField(
            model_name='item',
            name='greutate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
